
   [[command]]
    name            = "node-template"
    workDir         = "${PWD}"
    isTemplate      = true
    removeContainer = true
    impersonate     = true
    addGroups       = true
    isInteractive   = true
    requireEnvVars  = true
    image           = "node:18.15.0"
    volumes         = [
        "${PWD}:${PWD}",
        "${HOME}:${HOME}",
        "${SSH_AUTH_SOCK}:/run/ssh.sock",
        "/etc/passwd:/etc/passwd:ro",
        "/etc/group:/etc/group:ro",
        "/media/nils/code:/media/nils/code",
        "/tmp:/tmp",
        "/dev/shm:/dev/shm",
        "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket",
    ]

  [[command]]
        name = "node"
        template="node-template"
        entryPoint = "node"
        envvars         = [
          "PWD=${PWD}",
          "HOME=${HOME}"
        ]

  [[command]]
    name="npx"
    template="node-template"
    entryPoint = "npx"

  [[command]]
    name="yarn"
    template="node-template"
    entryPoint = "yarn"
    uniqueNames=true
    ports=["8081:8080"]
